### PR TITLE
Login form as well as signup form

### PR DESCRIPTION
**Pull request by neelshahasu**
Contains #52 and #53

### CODE REVIEW

**Comment by KirtanSoni** [comment]
Add screen shots to the description

**Comment by KirtanSoni** [comment]
Your Folder structure doesnt conform with the template in the main branch. Please fix that before we merge.

**Comment by mpraja11** [comment]
Add screenshots

**Comment by KirtanSoni** [comment]
@neelshahasu  The code doesnt work on IntelliJ.
The updates are not invoked in the tests so no way to see output

**Comment by neelshahasu** [comment]
Screenshot 2023-11-02 at 3 07 11 PM

**Comment by neelshahasu** [comment]
Screenshot 2023-11-02 at 3 07 11 PM

**Comment by neelshahasu** [comment]
Screenshot 2023-11-02 at 3 07 18 PM

**Pull request closed without merging**
