### PR TITLE
Us#86

### PR DESCRIPTION
**Pull request by mpraja11**
Home page is created and tested from my side. It is ready to merge, but I need you guys to review it.

### CODE REVIEW

**Comment by KirtanSoni** [comment]
Looks good @mpraja11  can u share screenshots of the homepage ui ?

**Comment by mpraja11** [comment]
image

**Comment by mpraja11** [comment]
image
image

**Review by KirtanSoni — COMMENTED** [review]
Looks good. adding to the main branch. Everyone make sure you have everything set up with swing before u run this.

**Comment by mpraja11** [comment]
why this branch has not been merged yet? no reviews?

**Review by sshah232 — APPROVED** [review]
Went through all the additions/changes! Seem to be perfectly fine to me.

**Comment by KirtanSoni** [comment]
Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
HomePageTests passed!
a warning is shown

**Comment by mpraja11** [comment]
> Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning. HomePageTests passed! a warning is shown @mpraja11

image

Other than Kirtan, is anyone having same warning while running Home Page? I have gone through some issues posted on internet, and found out that particularly some Mac OS devices having this issue. That is why I am asking your review, guys @sshah232 @BhattJanmay @neelshahasu

**Comment by KirtanSoni** [comment]
@mpraja11 You are correct, It appears on My screen. We should mention this on the readMe, all the Issues that are currently faced. Since this is not a bug that needs to be addressed right away i will create an issue in taiga with very small developer value.

**Comment by mpraja11** [comment]
> It appears on My screen. We should mention this on the readMe, all the Issues that are currently faced. Since this is not a bug that needs to be addressed right away i will create an issue in taiga with very small developer value.

Yes, this is not a bug technically, but it should be taken in consideration since it can create an issue on some devices.

**Pull request merged**
